
import React, { createContext, useState, useContext, useEffect } from 'react';

type Language = 'en' | 'hi' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isIndic: boolean;
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.analyze": "Analyze Crop",
    "nav.soil": "Soil Lab",
    "nav.production": "Smart Farm",
    "nav.profile": "Profile",
    "nav.login": "Log In",
    "nav.signup": "Sign Up",
    "nav.logout": "Sign Out",
    
    // Existing keys...
    "hero.badge": "AI-Powered Crop Protection",
    "hero.title.1": "Your Pocket",
    "hero.title.2": "Agronomist.",
    "hero.subtitle": "Diagnose crop diseases, get weather-smart treatments, and protect your yield—all from a single photo.",
    "hero.cta.detect": "Detect Disease",
    "hero.cta.demo": "Watch Demo",
    "hero.stat.accuracy": "Accuracy",
    "hero.stat.farmers": "Farmers",
    "hero.stat.access": "Access",
    "feat.detect": "Instant Detection",
    "feat.weather": "Weather Sync",
    "feat.protect": "Crop Protection",
    "why.title": "Why Farmers Trust Us",
    "why.subtitle": "We combine advanced AI with local farming wisdom to give you the best of both worlds.",
    "why.1.title": "Local Language Support",
    "why.1.desc": "We speak your language. Get diagnosis and advice in Hindi, Bengali, or English instantly.",
    "why.2.title": "Works Offline",
    "why.2.desc": "No internet in the field? No problem. Our app caches results and works on low bandwidth.",
    "why.3.title": "Zero Cost",
    "why.3.desc": "Completely free for smallholder farmers. We believe technology should be accessible to all.",
    "why.4.title": "Genuine Products",
    "why.4.desc": "We connect you to verified sellers so you never buy fake medicines again.",
    "trust.title": "Trusted by the Community",
    "trust.1.quote": "Saved my potato crop from blight. The audio guide is very helpful.",
    "trust.1.name": "Rajesh Kumar",
    "trust.1.loc": "Bihar",
    "trust.2.quote": "I like that it tells me when to spray based on the rain.",
    "trust.2.name": "Sunita Devi",
    "trust.2.loc": "Uttar Pradesh",
    "trust.3.quote": "Finally an app that speaks Bengali properly!",
    "trust.3.name": "Amit Roy",
    "trust.3.loc": "West Bengal",
    "faq.title": "Frequently Asked Questions",
    "faq.1.q": "Is this app really free?",
    "faq.1.a": "Yes, CropShield is 100% free for farmers to diagnose diseases and get advice.",
    "faq.2.q": "Does it work without internet?",
    "faq.2.a": "The app is optimized for 2G/3G. Once loaded, you can view past reports offline.",
    "faq.3.q": "How accurate is the AI?",
    "faq.3.a": "Our AI is trained on over 50,000 crop images and has a 98% accuracy rate.",
    "detect.lab_title": "AI Laboratory",
    "detect.title": "Farmer's Assistant",
    "detect.subtitle": "Upload a photo or take a picture. Get advice in your language.",
    "detect.upload": "Upload Crop Photo",
    "detect.drag": "Drag & drop or choose an option below",
    "detect.drop": "Drop image here",
    "detect.btn.file": "Choose File",
    "detect.btn.camera": "Take Photo",
    "detect.btn.remove": "Remove Image",
    "detect.btn.analyze": "Start Analysis",
    "detect.btn.analyzing": "Analyzing...",
    "detect.btn.consulting": "Consulting Expert...",
    "detect.btn.again": "Analyze Another",
    "detect.error.img": "Please upload a valid image file.",
    "detect.error.id": "Could not identify crop. Please ensure the photo is clear.",
    "detect.sample": "Or Use Sample",
    "detect.history_title": "Track Your Field History",
    "detect.history_sub": "Join 50k+ farmers to save reports and monitor farm growth.",
    "detect.signup_now": "Sign Up Now",
    "detect.promo.save": "Save your field reports",
    "detect.promo.desc": "Create a free account to track disease history and get alerts.",
    "detect.promo.btn": "Sign Up Free",
    "result.report_header": "Field Report",
    "result.confidence": "Confidence",
    "result.live_expert": "Live Expert",
    "result.call_assistant": "Call Assistant",
    "result.listen_learn": "Listen & Learn",
    "result.audio_guide": "Audio Guide",
    "result.generate_voice": "Generate Voice Advice",
    "result.field_env": "Field Environment",
    "result.condition": "Condition",
    "result.temp": "Temp",
    "result.humidity": "Humidity",
    "result.wind": "Wind",
    "result.share": "Share",
    "result.copied": "Copied to Clipboard!",
    "result.print": "Print",
    "result.diagnosis_title": "Full Diagnosis",
    "result.diagnosis_sub": "Detailed AI Analysis",
    "result.expand": "Click to Expand",
    "result.collapse": "Collapse",
    "result.safety_rule": "Vital Safety Rule",
    "result.organic_title": "Home Remedy (Organic)",
    "result.organic_sub": "Zero Cost Solution",
    "result.organic_cost": "Estimated Cost: FREE",
    "result.market_title": "Market Medicine (Chemical)",
    "result.market_sub": "Verified Recommendation",
    "result.active_molecule": "Active Molecule",
    "result.market_price": "Market Price",
    "result.usage_guide": "Usage Guide",
    "result.find_shops": "Find Genuine Sellers Near Me",
    "result.locating_shops": "Locating Nearby Sellers...",
    "result.chat_title": "Kisan Mitra AI Chat",
    "result.chat_sub": "Immediate Answers",
    "result.chat_placeholder": "Ask about prices, prevention...",
    "result.dosage": "Mix",
    "result.per_litre": "per litre",
    "result.frequency": "Frequency",
    "result.days": "days",
    "auth.join": "Join Us",
    "auth.join.subtitle": "Join the Community of Modern Farmers",
    "auth.welcome": "Welcome Back",
    "auth.login.subtitle": "Log in to access your farm dashboard",
    "auth.btn.login": "Log In",
    "auth.btn.signup": "Create Account",
    "auth.name": "Full Name",
    "auth.email": "Email Address",
    "auth.pass": "Password",
    "auth.loc": "Farm Location (Village/District)",
    "auth.size": "Farm Size (Acres)",
    "auth.crops": "Primary Crops",
    "auth.no_acct": "Don't have an account?",
    "auth.have_acct": "Already have an account?",
    "auth.link.signup": "Sign up free",
    "auth.link.login": "Log in here",
    "profile.scans": "Total Scans",
    "profile.issues": "Issues Found",
    "profile.healthy": "Healthy Crops",
    "profile.history": "Analysis History",
    "profile.no_history": "No scans yet",
    "profile.start": "Start First Scan",
    "profile.view": "View Report",
    "profile.match": "Match",

    // SOIL LAB
    "soil.title": "Digital Soil Laboratory",
    "soil.subtitle": "Scientific analysis using Satellite Data, Computer Vision, and OCR.",
    "soil.tab.satellite": "Satellite Data",
    "soil.tab.vision": "Visual Doctor",
    "soil.tab.ocr": "Health Card",
    "soil.sat.desc": "We use Open-Meteo and ISRIC data layers to estimate soil moisture, temperature, and pH based on your GPS location.",
    "soil.btn.fetch": "Fetch Satellite Data",
    "soil.label.moisture": "MOISTURE",
    "soil.label.temp": "TEMP",
    "soil.label.region": "REGION PROFILE",
    "soil.upload.vision": "Click to upload soil photo",
    "soil.upload.ocr": "Click to upload health card",
    "soil.btn.vision": "Analyze Texture",
    "soil.btn.ocr": "Scan Card Data",
    "soil.res.header": "Analysis Report",
    "soil.res.type": "SOIL TYPE",
    "soil.res.ph": "pH LEVEL",
    "soil.res.org": "ORGANIC CARBON",
    "soil.res.def": "Deficiencies",
    "soil.res.rec": "Recommendations",
    "soil.res.empty": "Select a method and start analysis to see the Soil Health Report.",

    // YIELD MASTER
    "yield.title": "Yield Master",
    "yield.subtitle": "AI-generated strategic production plans to maximize your harvest.",
    "yield.config_title": "Farm Configuration",
    "yield.label.crop": "Target Crop",
    "yield.label.land": "Land Size (Acres)",
    "yield.label.season": "Season",
    "yield.btn.generate": "Generate Plan",
    "yield.res.projected": "PROJECTED YIELD",
    "yield.res.timeline": "Growth Timeline",
    "yield.res.tips": "Agronomist Pro-Tips",
    "yield.res.fert": "Fertilizer",
    "yield.empty": "Enter details to generate your Yield Plan"
  },
  hi: {
    "nav.home": "होम",
    "nav.analyze": "जाँच",
    "nav.soil": "मिट्टी लैब",
    "nav.production": "स्मार्ट फार्म",
    "nav.profile": "प्रोफाइल",
    "nav.login": "लॉग इन",
    "nav.signup": "साइन अप",
    "nav.logout": "लॉग आउट",
    "hero.badge": "एआई-संचालित फसल सुरक्षा",
    "hero.title.1": "आपका डिजिटल",
    "hero.title.2": "कृषि मित्र",
    "hero.subtitle": "फसल रोगों की पहचान करें, मौसम-आधारित उपचार प्राप्त करें और अपनी पैदावार बचाएं—सिर्फ एक फोटो से।",
    "hero.cta.detect": "अभी जाँच करें",
    "hero.cta.demo": "डेमो देखें",
    "hero.stat.accuracy": "सटीकता",
    "hero.stat.farmers": "किसान",
    "hero.stat.access": "पहुंच",
    "feat.detect": "तुरंत पहचान",
    "feat.weather": "मौसम जानकारी",
    "feat.protect": "फसल सुरक्षा",
    "why.title": "किसान हम पर भरोसा क्यों करते हैं",
    "why.subtitle": "हम आपकी खेती में आधुनिक तकनीक और देसी समझ दोनों को जोड़ते हैं।",
    "why.1.title": "आपकी अपनी भाषा",
    "why.1.desc": "हम आपकी भाषा समझते हैं। हिंदी, बांग्ला या अंग्रेजी में तुरंत सलाह पाएं।",
    "why.2.title": "बिना इंटरनेट काम करे",
    "why.2.desc": "खेत में नेट नहीं? कोई बात नहीं। कम नेटवर्क में भी ऐप अच्छा चलता है।",
    "why.3.title": "बिलकुल मुफ्त",
    "why.3.desc": "छोटे किसानों के लिए यह सेवा मुफ्त है। तकनीक पर सबका हक है।",
    "why.4.title": "असली दवाएं",
    "why.4.desc": "हम आपको सही दुकानदारों से जोड़ते हैं ताकि आप नकली दवाओं से बचें।",
    "trust.title": "समुदाय का भरोसा",
    "trust.1.quote": "मेरी आलू की फसल को झुलसा रोग से बचाया। ऑडियो गाइड बहुत काम की है।",
    "trust.1.name": "राजेश कुमार",
    "trust.1.loc": "बिहार",
    "trust.2.quote": "मुझे यह पसंद है कि यह बारिश देखकर छिड़काव का समय बताता है।",
    "trust.2.name": "सुनीता देवी",
    "trust.2.loc": "उत्तर प्रदेश",
    "trust.3.quote": "आखिरकार एक ऐप जो सही हिंदी बोलता है!",
    "trust.3.name": "अमित रॉय",
    "trust.3.loc": "पश्चिम बंगाल",
    "faq.title": "अक्सर पूछे जाने वाले सवाल",
    "faq.1.q": "क्या यह ऐप सचमुच मुफ्त है?",
    "faq.1.a": "जी हाँ, क्रॉपशील्ड किसानों के लिए बीमारी पहचानने और सलाह लेने के लिए 100% मुफ्त है।",
    "faq.2.q": "क्या यह बिना इंटरनेट के चलता है?",
    "faq.2.a": "यह ऐप 2G/3G के लिए बना है। एक बार लोड होने पर आप पुरानी रिपोर्ट देख सकते हैं।",
    "faq.3.q": "एआई कितना सटीक है?",
    "faq.3.a": "हमारा एआई 50,000 से ज्यादा तस्वीरों पर सीखा है और 98% सही जवाब देता है।",
    "detect.lab_title": "एआई लैब",
    "detect.title": "किसान सहायक",
    "detect.subtitle": "फोटो अपलोड करें या तस्वीर लें। अपनी भाषा में सलाह प्राप्त करें।",
    "detect.upload": "फोटो अपलोड करें",
    "detect.drag": "फोटो यहाँ डालें या नीचे से चुनें",
    "detect.drop": "फोटो यहाँ छोड़ें",
    "detect.btn.file": "फ़ाइल चुनें",
    "detect.btn.camera": "फ़ोटो लें",
    "detect.btn.remove": "फ़ोटो हटाएँ",
    "detect.btn.analyze": "जाँच शुरू करें",
    "detect.btn.analyzing": "जाँच हो रही है...",
    "detect.btn.consulting": "विशेषज्ञ सलाह ले रहे हैं...",
    "detect.btn.again": "दूसरी जाँच करें",
    "detect.error.img": "कृपया सही फोटो अपलोड करें।",
    "detect.error.id": "फसल की पहचान नहीं हो सकी।",
    "detect.sample": "नमूना फोटो",
    "detect.history_title": "अपनी रिपोर्ट ट्रैक करें",
    "detect.history_sub": "रिपोर्ट सहेजने के लिए 50k+ किसानों से जुड़ें।",
    "detect.signup_now": "अभी रजिस्टर करें",
    "detect.promo.save": "अपनी रिपोर्ट सेव करें",
    "detect.promo.desc": "बीमारी का इतिहास रखने और अलर्ट पाने के लिए मुफ्त खाता बनाएं।",
    "detect.promo.btn": "मुफ्त साइन अप",
    "result.report_header": "क्षेत्र रिपोर्ट",
    "result.confidence": "सटीकता",
    "result.live_expert": "एआई विशेषज्ञ",
    "result.call_assistant": "कॉल करें",
    "result.listen_learn": "सुनें और सीखें",
    "result.audio_guide": "ऑडियो मार्गदर्शिका",
    "result.generate_voice": "ऑडियो सलाह सुनें",
    "result.field_env": "खेत का माहौल",
    "result.condition": "मौसम",
    "result.temp": "तापमान",
    "result.humidity": "नमी",
    "result.wind": "हवा",
    "result.share": "शेयर",
    "result.copied": "कॉपी किया गया!",
    "result.print": "प्रिंट",
    "result.diagnosis_title": "पूर्ण बीमारी निदान",
    "result.diagnosis_sub": "विस्तृत एआई रिपोर्ट",
    "result.expand": "विस्तार के लिए क्लिक करें",
    "result.collapse": "छोटा करें",
    "result.safety_rule": "जरूरी सुरक्षा नियम",
    "result.organic_title": "घरेलू/जैविक उपाय",
    "result.organic_sub": "मुफ्त समाधान",
    "result.organic_cost": "अनुमानित लागत: मुफ्त",
    "result.market_title": "बाजार की रासायनिक दवा",
    "result.market_sub": "प्रमाणित दवा",
    "result.active_molecule": "दवा का नाम",
    "result.market_price": "बाजार मूल्य",
    "result.usage_guide": "उपयोग का तरीका",
    "result.find_shops": "पास के विक्रेता खोजें",
    "result.locating_shops": "दुकानें खोजी जा रही हैं...",
    "result.chat_title": "किसान मित्र चैट",
    "result.chat_sub": "तुरंत सहायता",
    "result.chat_placeholder": "सवाल पूछें...",
    "result.dosage": "मिलाएं",
    "result.per_litre": "प्रति लीटर",
    "result.frequency": "छिड़काव",
    "result.days": "दिन",
    "auth.join": "जुड़ें",
    "auth.join.subtitle": "आधुनिक किसानों के समुदाय में शामिल हों",
    "auth.welcome": "वापसी पर स्वागत",
    "auth.login.subtitle": "अपने डैशबोर्ड के लिए लॉग इन करें",
    "auth.btn.login": "लॉग इन",
    "auth.btn.signup": "खाता बनाएं",
    "auth.name": "पूरा नाम",
    "auth.email": "ईमेल पता",
    "auth.pass": "पासवर्ड",
    "auth.loc": "खेत का स्थान (गाँव/जिला)",
    "auth.size": "खेत का आकार (एकड़)",
    "auth.crops": "मुख्य फसलें",
    "auth.no_acct": "खाता नहीं है?",
    "auth.have_acct": "पहले से खाता है?",
    "auth.link.signup": "मुफ्त रजिस्टर करें",
    "auth.link.login": "यहाँ लॉग इन करें",
    "profile.scans": "कुल स्कैन",
    "profile.issues": "बीमारियाँ मिलीं",
    "profile.healthy": "स्वस्थ फसल",
    "profile.history": "जाँच का इतिहास",
    "profile.no_history": "अभी कोई स्कैन नहीं",
    "profile.start": "पहला स्कैन करें",
    "profile.view": "रिपोर्ट देखें",
    "profile.match": "मिलान",

    // SOIL LAB
    "soil.title": "डिजिटल मिट्टी लैब",
    "soil.subtitle": "सैटेलाइट डेटा, कंप्यूटर विज़न और ओसीआर का उपयोग करके वैज्ञानिक विश्लेषण।",
    "soil.tab.satellite": "सैटेलाइट डेटा",
    "soil.tab.vision": "विजुअल डॉक्टर",
    "soil.tab.ocr": "हेल्थ कार्ड",
    "soil.sat.desc": "हम आपके जीपीएस स्थान के आधार पर मिट्टी की नमी, तापमान और पीएच का अनुमान लगाने के लिए ओपन-मेटियो और ISRIC डेटा का उपयोग करते हैं।",
    "soil.btn.fetch": "सैटेलाइट डेटा लाएं",
    "soil.label.moisture": "नमी",
    "soil.label.temp": "तापमान",
    "soil.label.region": "क्षेत्र प्रोफाइल",
    "soil.upload.vision": "मिट्टी की फोटो अपलोड करें",
    "soil.upload.ocr": "हेल्थ कार्ड अपलोड करें",
    "soil.btn.vision": "बनावट का विश्लेषण करें",
    "soil.btn.ocr": "कार्ड स्कैन करें",
    "soil.res.header": "विश्लेषण रिपोर्ट",
    "soil.res.type": "मिट्टी का प्रकार",
    "soil.res.ph": "pH स्तर",
    "soil.res.org": "जैविक कार्बन",
    "soil.res.def": "कमियाँ",
    "soil.res.rec": "सुझाव",
    "soil.res.empty": "मिट्टी की स्वास्थ्य रिपोर्ट देखने के लिए एक विधि चुनें और विश्लेषण शुरू करें।",

    // YIELD MASTER
    "yield.title": "यीड मास्टर (पैदावार)",
    "yield.subtitle": "अपनी फसल को अधिकतम करने के लिए एआई-जनरेटेड उत्पादन योजनाएं।",
    "yield.config_title": "खेत का कॉन्फ़िगरेशन",
    "yield.label.crop": "लक्षित फसल",
    "yield.label.land": "भूमि का आकार (एकड़)",
    "yield.label.season": "मौसम",
    "yield.btn.generate": "योजना बनाएं",
    "yield.res.projected": "अनुमानित पैदावार",
    "yield.res.timeline": "विकास समयरेखा",
    "yield.res.tips": "कृषि विशेषज्ञ के सुझाव",
    "yield.res.fert": "उर्वरक",
    "yield.empty": "अपनी पैदावार योजना बनाने के लिए विवरण दर्ज करें"
  },
  bn: {
    "nav.home": "হোম",
    "nav.analyze": "যাচাই",
    "nav.soil": "মাটি ল্যাব",
    "nav.production": "স্মার্ট ফার্ম",
    "nav.profile": "প্রোফাইল",
    "nav.login": "লগ ইন",
    "nav.signup": "সাইন আপ",
    "nav.logout": "লগ আউট",
    "hero.badge": "এআই-চালিত শস্য সুরক্ষা",
    "hero.title.1": "আপনার পকেটে",
    "hero.title.2": "কৃষি বিশেষজ্ঞ",
    "hero.subtitle": "ফসলের রোগ নির্ণয় করুন এবং আপনার ফলন রক্ষা করুন—শুধুমাত্র একটি ছবি দিয়ে।",
    "hero.cta.detect": "রোগ শনাক্ত করুন",
    "hero.cta.demo": "ডেমো দেখুন",
    "hero.stat.accuracy": "নির্ভুলতা",
    "hero.stat.farmers": "কৃষক",
    "hero.stat.access": "অ্যাক্সেস",
    "feat.detect": "দ্রুত শনাক্তকরণ",
    "feat.weather": "আবহাওয়ার তথ্য",
    "feat.protect": "ফসল সুরক্ষা",
    "why.title": "কৃষকরা কেন আমাদের বিশ্বাস করেন",
    "why.subtitle": "আমরা আধুনিক প্রযুক্তির সাথে স্থানীয় চাষাবাদের অভিজ্ঞতাকে যুক্ত করি।",
    "why.1.title": "আপনার নিজের ভাষা",
    "why.1.desc": "আমরা আপনার ভাষা বুঝি। বাংলা, হিন্দি বা ইংরেজিতে তাৎক্ষণিক পরামর্শ পান।",
    "why.2.title": "ইন্টারনেট ছাড়াও চলে",
    "why.2.desc": "মাঠে নেট নেই? সমস্যা নেই। কম নেটওয়ার্ক স্পিডেও আমাদের অ্যাপ ভালো কাজ করে।",
    "why.3.title": "সম্পূর্ণ বিনামূল্যে",
    "why.3.desc": "ক্ষুদ্র কৃষকদের জন্য এই সেবা সম্পূর্ণ ফ্রি। প্রযুক্তিতে সবার অধিকার আছে।",
    "why.4.title": "আসল ওষুধ",
    "why.4.desc": "আমরা আপনাকে সঠিক বিক্রেতাদের সাথে সংযুক্ত করি যাতে আপনি নকল ওষুধ কেনা থেকে বাঁচেন।",
    "trust.title": "কমিউনিটির বিশ্বাস",
    "trust.1.quote": "আমার আলুর ফসলকে ধসা রোগ থেকে বাঁচিয়েছে। অডিও গাইডটি খুব কাজের।",
    "trust.1.name": "রাজেশ কুমার",
    "trust.1.loc": "বিহার",
    "trust.2.quote": "বৃষ্টির সম্ভাবনা দেখে স্প্রে করার সময় বলে দেয়, এটা আমার খুব ভালো লাগে।",
    "trust.2.name": "সুনিতা দেবী",
    "trust.2.loc": "উত্তর প্রদেশ",
    "trust.3.quote": "অবশেষে এমন একটা অ্যাপ যা সঠিকভাবে বাংলা বলে!",
    "trust.3.name": "অমিত রায়",
    "trust.3.loc": "পশ্চিমবঙ্গ",
    "faq.title": "সাধারণ জিজ্ঞাসা",
    "faq.1.q": "এই অ্যাপটি কি সত্যিই ফ্রি?",
    "faq.1.a": "হ্যাঁ, ক্রপশিল্ড কৃষকদের রোগ নির্ণয় এবং পরামর্শের জন্য ১০০% বিনামূল্যে।",
    "faq.2.q": "এটি কি ইন্টারনেট ছাড়া কাজ করে?",
    "faq.2.a": "অ্যাপটি 2G/3G এর জন্য তৈরি। একবার লোড হলে আপনি অফলাইনে রিপোর্ট দেখতে পারবেন।",
    "faq.3.q": "এআই কতটা নির্ভুল?",
    "faq.3.a": "আমাদের এআই ৫০,০০০+ ছবির উপর প্রশিক্ষিত এবং ৯৮% সঠিক উত্তর দেয়।",
    "detect.lab_title": "এআই ল্যাব",
    "detect.title": "কৃষক সহকারী",
    "detect.subtitle": "ছবি আপলোড করুন বা তুলুন। আপনার ভাষায় পরামর্শ নিন।",
    "detect.upload": "ছবি আপলোড করুন",
    "detect.drag": "ছবি এখানে দিন বা নিচে থেকে বেছে নিন",
    "detect.drop": "ছবি এখানে ছাড়ুন",
    "detect.btn.file": "ফাইল বাছুন",
    "detect.btn.camera": "ছবি তুলুন",
    "detect.btn.remove": "ছবি সরান",
    "detect.btn.analyze": "যাচাই শুরু করুন",
    "detect.btn.analyzing": "যাচাই চলছে...",
    "detect.btn.consulting": "বিশেষজ্ঞ পরামর্শ নিচ্ছেন...",
    "detect.btn.again": "আরেকটি যাচাই করুন",
    "detect.error.img": "সঠিক ছবি আপলোড করুন।",
    "detect.error.id": "শনাক্ত করা যায়নি। পরিষ্কার ছবি তুলুন।",
    "detect.sample": "নমুনা ছবি",
    "detect.history_title": "আপনার রেকর্ড ট্র্যাক করুন",
    "detect.history_sub": "রিপোর্ট সেভ করতে ৫০ হাজার কৃষকের সাথে যোগ দিন।",
    "detect.signup_now": "এখনই সাইন আপ করুন",
    "detect.promo.save": "রিপোর্ট সেভ করুন",
    "detect.promo.desc": "রোগের ইতিহাস রাখতে এবং অ্যালার্ট পেতে ফ্রি অ্যাকাউন্ট খুলুন।",
    "detect.promo.btn": "ফ্রি সাইন আপ",
    "result.report_header": "মাঠের রিপোর্ট",
    "result.confidence": "সঠিকতা",
    "result.live_expert": "এআই বিশেষজ্ঞ",
    "result.call_assistant": "কল করুন",
    "result.listen_learn": "শুনুন ও শিখুন",
    "result.audio_guide": "অডিও গাইড",
    "result.generate_voice": "অডিও পরামর্শ নিন",
    "result.field_env": "মাঠের পরিবেশ",
    "result.condition": "আবহাওয়া",
    "result.temp": "তাপমাত্রা",
    "result.humidity": "আর্দ্রতা",
    "result.wind": "বাতাস",
    "result.share": "শেয়ার",
    "result.copied": "কপি করা হয়েছে!",
    "result.print": "প্রিন্ট",
    "result.diagnosis_title": "সম্পূর্ণ রোগ নির্ণয়",
    "result.diagnosis_sub": "বিস্তারিত এআই রিপোর্ট",
    "result.expand": "বিস্তারিত দেখতে ক্লিক করুন",
    "result.collapse": "সংক্ষিপ্ত করুন",
    "result.safety_rule": "সুরক্ষা নিয়ম",
    "result.organic_title": "ঘরোয়া প্রতিকার (জৈব)",
    "result.organic_sub": "বিনা খরচে সমাধান",
    "result.organic_cost": "আনুমানিক খরচ: ফ্রি",
    "result.market_title": "বাজারের রাসায়নিক ওষুধ",
    "result.market_sub": "যাচাইকৃত ওষুধ",
    "result.active_molecule": "ওষুধের নাম",
    "result.market_price": "বাজার মূল্য",
    "result.usage_guide": "ব্যবহারের নিয়ম",
    "result.find_shops": "কাছাকাছি বিক্রেতা খুঁজুন",
    "result.locating_shops": "দোকান খোঁজা হচ্ছে...",
    "result.chat_title": "কৃষি মিত্র চ্যাট",
    "result.chat_sub": "তাত্ক্ষণিক উত্তর",
    "result.chat_placeholder": "প্রশ্ন জিজ্ঞাসা করুন...",
    "result.dosage": "মেশান",
    "result.per_litre": "প্রতি লিটার",
    "result.frequency": "ব্যবহার",
    "result.days": "দিন",
    "auth.join": "যোগ দিন",
    "auth.join.subtitle": "আধুনিক কৃষকদের সম্প্রদায়ে যোগ দিন",
    "auth.welcome": "স্বাগতম",
    "auth.login.subtitle": "আপনার ড্যাশবোর্ডে লগ ইন করুন",
    "auth.btn.login": "লগ ইন",
    "auth.btn.signup": "অ্যাকাউন্ট তৈরি করুন",
    "auth.name": "পুরো নাম",
    "auth.email": "ইমেল ঠিকানা",
    "auth.pass": "পাসওয়ার্ড",
    "auth.loc": "খামারের অবস্থান (গ্রাম/জেলা)",
    "auth.size": "খামারের আকার (একর)",
    "auth.crops": "প্রধান ফসল",
    "auth.no_acct": "অ্যাকাউন্ট নেই?",
    "auth.have_acct": "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    "auth.link.signup": "ফ্রি সাইন আপ",
    "auth.link.login": "এখানে লগ ইন করুন",
    "profile.scans": "মোট স্ক্যান",
    "profile.issues": "রোগ শনাক্ত",
    "profile.healthy": "সুস্থ ফসল",
    "profile.history": "যাচাইয়ের ইতিহাস",
    "profile.no_history": "এখনও কোন স্ক্যান নেই",
    "profile.start": "প্রথম স্ক্যান শুরু করুন",
    "profile.view": "রিপোর্ট দেখুন",
    "profile.match": "মিল",

    // SOIL LAB
    "soil.title": "ডিজিটাল মাটি ল্যাব",
    "soil.subtitle": "স্যাটেলাইট ডেটা, কম্পিউটার ভিশন এবং ওসিআর ব্যবহার করে বৈজ্ঞানিক বিশ্লেষণ।",
    "soil.tab.satellite": "স্যাটেলাইট ডেটা",
    "soil.tab.vision": "ভিজ্যুয়াল ডাক্তার",
    "soil.tab.ocr": "হেলথ কার্ড",
    "soil.sat.desc": "আমরা আপনার জিপিএস অবস্থানের উপর ভিত্তি করে মাটির আর্দ্রতা, তাপমাত্রা এবং পিএইচ অনুমান করতে ওপেন-মেটিও এবং ISRIC ডেটা ব্যবহার করি।",
    "soil.btn.fetch": "স্যাটেলাইট তথ্য নিন",
    "soil.label.moisture": "আর্দ্রতা",
    "soil.label.temp": "তাপমাত্রা",
    "soil.label.region": "অঞ্চলের প্রোফাইল",
    "soil.upload.vision": "মাটির ছবি আপলোড করুন",
    "soil.upload.ocr": "হেলথ কার্ড আপলোড করুন",
    "soil.btn.vision": "টেক্সচার বিশ্লেষণ করুন",
    "soil.btn.ocr": "কার্ড স্ক্যান করুন",
    "soil.res.header": "বিশ্লেষণ রিপোর্ট",
    "soil.res.type": "মাটির ধরন",
    "soil.res.ph": "pH লেভেল",
    "soil.res.org": "জৈব কার্বন",
    "soil.res.def": "ঘাটতি",
    "soil.res.rec": "সুপারিশ",
    "soil.res.empty": "মাটির স্বাস্থ্য রিপোর্ট দেখতে একটি পদ্ধতি নির্বাচন করুন এবং বিশ্লেষণ শুরু করুন।",

    // YIELD MASTER
    "yield.title": "ইল্ড মাস্টার (ফলন)",
    "yield.subtitle": "আপনার ফলন বাড়ানোর জন্য এআই-জেনারেটেড উৎপাদন পরিকল্পনা।",
    "yield.config_title": "খামারের কনফিগারেশন",
    "yield.label.crop": "লক্ষ্য ফসল",
    "yield.label.land": "জমির পরিমাণ (একর)",
    "yield.label.season": "ঋতু",
    "yield.btn.generate": "পরিকল্পনা তৈরি করুন",
    "yield.res.projected": "প্রত্যাশিত ফলন",
    "yield.res.timeline": "বৃদ্ধির সময়রেখা",
    "yield.res.tips": "কৃষি বিশেষজ্ঞের টিপস",
    "yield.res.fert": "সার",
    "yield.empty": "আপনার ফলন পরিকল্পনা তৈরি করতে বিবরণ লিখুন"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const storedLang = localStorage.getItem('cropShield_lang') as Language;
    if (storedLang && ['en', 'hi', 'bn'].includes(storedLang)) {
      setLanguage(storedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('cropShield_lang', lang);
  };

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  const isIndic = language === 'hi' || language === 'bn';

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isIndic }}>
      <div className={isIndic ? 'font-bengali' : 'font-sans'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
